name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        dotnet: ['5.0.x', '3.1.x']
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        include:
        - os: 'windows-latest'
          platformname: 'windows'
        - os: 'ubuntu-latest'
          platformname: 'linux'
        - os: 'macos-latest'
          platformname: 'mac'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: cache nuget
      uses: actions/cache@v2.1.6
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -o "hShopCLI-${{matrix.platformname}}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: hShopCLI-${{matrix.platformname}}
        path: hShopCLI-${{matrix.platformname}}
        retention-days: 60
      
